apiVersion: v1
kind: Service
metadata:
  name: learner-service
  labels:
    name: learner-service
    app: learner
spec:
  selector:
    name: learner-service-pod
    app: learner-service
  ports:
    - protocol: TCP
      port: 80 # The port on the service
      nodePort: 30008
      targetPort: 3002 # The port your frontend Pod is listening on
  type: NodePort # This can be NodePort, ClusterIP, or LoadBalancer depending on your setup
