apiVersion: v1
kind: Pod
metadata:
  name: learner-service-pod
  labels:
    name: learner-service-pod
    app: learner-service
spec:
  containers:
  - name: learner-service
    image: malithiroshan/educonnect-learner-service:v1.0
    ports:
    - containerPort: 3002
