apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    name: payment-service
    app: payment
spec:
  selector:
    name: payment-service-pod
    app: payment-service
  ports:
    - protocol: TCP
      port: 80 # The port on the service
      nodePort: 30006
      targetPort: 3003 # The port your frontend Pod is listening on
  type: NodePort # This can be NodePort, ClusterIP, or LoadBalancer depending on your setup
