version: "3.9"

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build: 
      context: ./BACKEND
    ports:
      - "5050:5050"
    volumes:
      - logs:/server/logs
    depends_on:
      - mongodb

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: