apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: frontend
spec:
  containers:
  - name: frontend-app
    image: malithiroshan/educonnect-frontend:latest
    ports:
    - containerPort: 5173
