apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    name: frontend-deploy
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-pod
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        name: frontend-pod
        app: frontend
    spec:
      containers:
      - name: frontend-app
        image: malithiroshan/educonnect-frontend:latest
        ports:
        - containerPort: 5173