apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend-service
    app: frontend
spec:
  selector:
    name: frontend-pod
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # The port on the service
      nodePort: 30005
      targetPort: 5173 # The port your frontend Pod is listening on
  type: NodePort # This can be NodePort, ClusterIP, or LoadBalancer depending on your setup
